# .travis.yml
sudo: false
language: php

php:
  - 7.2

env:
  - TYPO3_VERSION=^9

addons:
  apt:
    packages:
      - parallel

install:
  - composer require typo3/minimal:${TYPO3_VERSION}
  - git checkout composer.json
  - export TYPO3_PATH_WEB="$PWD/.build/web"

jobs:
  include:
    - stage: quality
      php: 7.2
      script: composer cgl

cache:
  directories:
    - $HOME/.composer/cache